name: Publish models package

on:
  push:
    branches:
      - master
    paths:
      - 'packages/models/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: checkout
    - uses: actions/setup-node@v1
      name: Install node.js
      with:
        node-version: '10.x'
    - run: npm install
      name: Install dependencies
      working-directory: packages/models
    - run: npm run test:prod && npm run build
      name: Build
      working-directory: packages/models
    - run: npm run semantic-release
      name: Publish
      working-directory: packages/models
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_PUBLISH_TOKEN }}
